; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]

[env:oat]
platform = ststm32
board = nucleo_g0b1re
framework = arduino
upload_protocol = stlink
board_build.code = maple
board_build.mcu = stm32g0b1ret6
board_build.f_cpu = 8000000L
build_flags =
    ${env.build_flags}
    -D BOARD=BOARD_BTT_SKR_MINI_E3_V3_0
    -D ENABLE_HWSERIAL2     ; This is the TFT port that can be used for debugging or GPS
    -D DEBUG_LEVEL=DEBUG_ANY
    -D USBCON
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBD_VID=0x0483
    -D USBD_PID=0x5740
    -D USB_MANUFACTURER="Open Astro"
    -D USB_PRODUCT="\"Open Astro Tracker\""
    -Wno-deprecated-declarations
lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.2
    teemuatlut/TMCStepper @ ^0.7.1
    waspinator/AccelStepper @ ^1.61

