/////////////////////////////////////////////////////////////////////////////////////////////////////////
// This configuration file was generated by the OpenAstroTech Configurator at https://config.openastrotech.com
// and is for firmware to be used on a OpenAstroTracker.
// Save this as Configuration_local.hpp in the folder where you placed the firmware code.
/////////////////////////////////////////////////////////////////////////////////////////////////////////
// Unique ConfigKey: TR:OAT,FWT:L,HS:N,SL:O,BD:M21,RST:N9,RDO:TU,RATP900:O90:A3000:V1800:S32:T256:,RTR:Y,RT:1,DS:N9,DDT:TU,DATP900:O90:A3000:V1800:S32:T256:,DT:1,DLIN90:D45:,STL:S,DY:NO,IDY:NO,GP:Y,LM:Y,FC:N,APT:N,RAH:N
/////////////////////////////////////////////////////////////////////////////////////////////////////////

//#pragma message("Including Configuration_local_bttskrminie3v30.hpp")

// We live in the Northern Hemisphere
#define NORTHERN_HEMISPHERE 1

// To use the much higher performance stepper library uncomment the next line.
// #define NEW_STEPPER_LIB

#if defined(BOARD) && BOARD != BOARD_BTT_SKR_MINI_E3_V3_0
    #error Selected PIO environment does not match this configuration
#else
    #define BOARD BOARD_BTT_SKR_MINI_E3_V3_0
#endif

////////////////////////////////
// RA Stepper configuration (OAT)
// See supported stepper values. Change according to the steppers you are using
// Using the NEMA 17, 1.8°/step stepper for RA
#define RA_STEPPER_TYPE STEPPER_TYPE_ENABLED
#define RA_STEPPER_SPR	400

// Using the TMC2209-UART driver for RA stepper motor
#define RA_DRIVER_TYPE DRIVER_TYPE_TMC2209_UART

// Define some RA stepper motor settings
#define RA_MOTOR_CURRENT_RATING        900 // mA
#define RA_OPERATING_CURRENT_SETTING   90 // %
#define RA_STEPPER_ACCELERATION        10000
// TODO: (MWK) TMC2209 Datasheet indicates that stall guard may not be accurate at speeds less than 1RPS (section 11.5)
// That would mean for a 200 step/revolution motor and 32 microsteps/step we would need a homing speed of 6400
// With a base stepper frequency of 2kHz, we can't generate 6.4kHz steps/sec.
// I've changed the base frequency from 500uS to 50uS (20kHz) which allows for 200 or 400 steps/revolution at 32 microsteps/step and
// some head room.
#define RA_SLEW_MICROSTEPPING          16
#define RA_TRACKING_MICROSTEPPING      256
#define RA_STEPPER_SPEED               RA_STEPPER_SPR * RA_SLEW_MICROSTEPPING   // 1 RPS

// Range is 0-255 - and is multiplied by 2 in the TMC driver, then compared to SG_RESULT: If SG_RESULT falls *below* this
// 2x value, it is considered a stall. 
#define RA_STALL_VALUE                 90   // SG_RESULT < 180 after TSTEP is < 400
#define RA_TCOOLTHRS                   400

// Is it going the wrong way?
#define RA_INVERT_DIR  1

#ifdef NEW_STEPPER_LIB
  #define RA_SLEWING_ACCELERATION_DEG   2.0  // deg/s/s
  #define RA_SLEWING_SPEED_DEG          2.0  // deg/s
#endif

// Track immediately after boot
#define TRACK_ON_BOOT 1

// Define limits for RA... 
#define RA_LIMIT_LEFT     5.5f
#define RA_LIMIT_RIGHT    6.5f
#define RA_TRACKING_LIMIT 6.75f // can't quite get to 7h...

// Using the 16 tooth gear (recommended) for RA belt
#define RA_PULLEY_TEETH 16

////////////////////////////////
// DEC Stepper configuration 
// See supported stepper values. Change according to the steppers you are using
// Using the NEMA 17, 1.8°/step stepper for DEC
#define DEC_STEPPER_TYPE STEPPER_TYPE_ENABLED
#define DEC_STEPPER_SPR	400
#define DEC_WHEEL_CIRCUMFERENCE        565.5f

// Using the TMC2209-UART driver for DEC stepper
#define DEC_DRIVER_TYPE DRIVER_TYPE_TMC2209_UART

// Define some DEC stepper motor settings
#define DEC_MOTOR_CURRENT_RATING       900 // mA
#define DEC_OPERATING_CURRENT_SETTING  90 // %
#define DEC_STEPPER_ACCELERATION       10000
#define DEC_SLEW_MICROSTEPPING         16
#define DEC_GUIDE_MICROSTEPPING        256
#define DEC_STEPPER_SPEED              DEC_STEPPER_SPR * DEC_SLEW_MICROSTEPPING
#define DEC_STALL_VALUE                90   // SG_RESULT < 180 after TSTEP is < 400
#define DEC_TCOOLTHRS                  400  // Velocities below which to disable StallGuard and Coolstep

// Is it going the wrong way?
#define DEC_INVERT_DIR  0

#ifdef NEW_STEPPER_LIB
  #define DEC_SLEWING_ACCELERATION_DEG   2.0  // degs/s/s
  #define DEC_SLEWING_SPEED_DEG          2.0  // deg/s
#endif

// Using the 16 tooth gear (recommended) for DEC belt
#define DEC_PULLEY_TEETH 16

// Define DEC limits
#define DEC_LIMIT_UP   90 // degrees from Home
#define DEC_LIMIT_DOWN 45 // degrees from Home

// TMC2209 Stealth Mode (spreadCycle) - When set to 0, tracking is more precise, but noisy (high-pitched hissing sound). When set to 1, they are silent.
#define RA_UART_STEALTH_MODE      1
#define DEC_UART_STEALTH_MODE     1

////////////////////////////////
// Display configuration 
// Define the type of display we are using. Currently: No display
#define DISPLAY_TYPE DISPLAY_TYPE_NONE

////////////////////////////////
// InfoDisplay configuration 
// Define the type of info display we are using. Currently: No info display
#define INFO_DISPLAY_TYPE          INFO_DISPLAY_TYPE_NONE
//#define INFO_DISPLAY_I2C_ADDRESS   0x3C
//#define INFO_DISPLAY_I2C_SDA_PIN   20
//#define INFO_DISPLAY_I2C_SCL_PIN   21
// Note that the E1 port is not usable since I2C requires pin 21!

////////////////////////////////
// GPS Addon configuration 
// Define whether we have the GPS addon or not. Currently: GPS NEO-6M
#define USE_GPS 1

////////////////////////////////
// Digital Level Addon configuration 
// Define whether we have the Digital Level or not. Currently: MPU-6050 Gyroscope
#define USE_GYRO_LEVEL 1
#define GYRO_AXIS_SWAP 0
//#define USE_GYRO_WITH_SOFTWAREI2C 1
#define GYRO_SOFTWARE_SCL_PIN PA9
#define GYRO_SOFTWARE_SDA_PIN PA10

////////////////////////////////
// Focuser configuration 
// Define whether to support a focusing stepper motor on E1 or not. Currently: No Focuser
// No Focuser settings

////////////////////////////////
// AutoPA Addon configuration 
// Define whether we have the AutoPA add on or not. Currently: No AutoPA
// No AutoPA settings

////////////////////////////////
// Auto Homing addons
#define USE_HALL_SENSOR_RA_AUTOHOME 0

///////////////////////
// Debug settings
#define DEBUG_LEVEL (DEBUG_MOUNT|DEBUG_STEPPERS|DEBUG_GYRO|DEBUG_GPS|DEBUG_COORD_CALC) // |DEBUG_MOUNT_VERBOSE)
//#define DEBUG_LEVEL (DEBUG_NONE)

